theme = "rose-pine"

[editor]
line-number = "relative"
bufferline = "always"
scroll-lines = "2"
soft-wrap.enable = true
file-picker.hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "file-modification-indicator"]

[keys.normal]
gc = "toggle_comments"

[keys.normal.space]
w = ":write"
q = ":quit-all"

