theme = "base16_transparent"

[editor]
line-number = "relative"
bufferline = "always"
scroll-lines = 2
soft-wrap.enable = true
file-picker.hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]

[keys.normal]
ret = "goto_word"
tab = ":bn"
S-tab = ":bp"

[keys.normal.space]
w = ":write"
q = ":qa"
x = ":bc"
f = "file_picker_in_current_directory"
F = "file_picker_in_current_buffer_directory"
