[font]
size=12
[font.normal]
family="Hack Nerd Font"
style="Mono"

[colors.normal]
black   = "0x050505"
blue    = "0x0077b6"
cyan    = "0x219ebc"
green   = "0x97a97c"
magenta = "0x9fa0ff"
red     = "0xd08c60"
white   = "0xe6ccb2"
yellow  = "0xffcb70"

[colors.primary]
background = "0x050505"
foreground = "#ffffff"
