# -- Basic Settings ------------------------------------------
set -g prefix C-b
set -g escape-time 10
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on

# -- Status Bar ---------------------------------------------
set -g status-position top
set -g status-interval 5
set -g status-left "#{host} "
set -g status-left-length 50
set -g status-right ""
set -g window-status-format "#I:#W"

run-shell ~/.config/tmux/plugins/sensible/sensible.tmux
# run-shell ~/.config/tmux/plugins/pain-control/pain_control.tmux
