# iterm2 pastel dark
[colors.primary]
background = '#000000'
foreground = '#bbbbbb'

[colors.cursor]
text = '#ffffff'
cursor = '#ffa560'

[colors.selection]
text = '#f1f1f1'
background = '#353883'

[colors.normal]
black   = '#4f4f4f'
red     = '#ff6c60'
green   = '#a8ff60'
yellow  = '#ffffb6'
blue    = '#96cbfe'
magenta = '#ff73fd'
cyan    = '#c6c5fe'
white   = '#eeeeee'

[colors.bright]
black   = '#7c7c7c'
red     = '#ffb6b0'
green   = '#ceffcf'
yellow  = '#ffffcc'
blue    = '#b5dcff'
magenta = '#ff9cfe'
cyan    = '#dfdfdf'
white   = '#ffffff'
